SitecoreBlog/Models/SearchModel.cs
using Sitecore.ContentSearch;
using Sitecore.ContentSearch.SearchTypes;
using System.Collections.Generic;

namespace SitecoreBlog.Models
{
    public class SearchBlog: SearchResultItem
    {
        [IndexField("_name")]
        public virtual string BlogName { get; set; }

        [IndexField("shortdescription_t")]
        public virtual string ShortDescription { get; set; }

        [IndexField("longdescription_t")]
        public virtual string LongDescription { get; set; }

        [IndexField("title_t")]
        public virtual string BlogTitle { get; set; }
        [IndexField("blogid_t")]
        public virtual string BlogId { get; set; }
        [IndexField("_template")]
        public virtual string TemplateID { get; set; }
    }

    public class BlogSearchResult
    {
        public string BlogId { get; set; }
    }

    /// <summary>
    /// Custom search result model for binding to front end
    /// </summary>
    public class BlogSearchResults
    {
        public List<BlogSearchResult> Results { get; set; }
    }
}

SitecoreBlog/Controllers/SitecoreBlogController.cs
using Sitecore.ContentSearch;
using Sitecore.ContentSearch.Linq;
using Sitecore.ContentSearch.Linq.Utilities;
using SitecoreBlog.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Web;
using System.Web.Mvc;

namespace SitecoreBlog.Controllers
{
    public class SitecoreBlogController : Controller
    {
        public ActionResult GetArticleList()
        {
            return View("~/Views/SitecoreBlog/ArticleList.cshtml", GetItems());
        }
        public ActionResult DemoComponent()
        {

            var item = Sitecore.Context.Database.GetItem("{97108A05-9C12-4700-A39A-F6B69B613A98}");
                
            return View("~/Views/SitecoreBlog/ControllerDemo.cshtml", item);
        }
        public ActionResult DoSearch(string searchText)
        {
            //return View("~/Views/SitecoreBlog/ArticleList.cshtml", GetItems().Where(x => x != null).Where(x => x.Fields["Title"].Value.Contains(searchText)
            //|| x.Fields["ShortDescription"].Value.Contains(searchText)));
            return View("~/Views/SitecoreBlog/Index.cshtml", GetItems().Where(x => x != null).Where(x => x.Fields["Title"].Value.Contains(searchText)
            || x.Fields["ShortDescription"].Value.Contains(searchText)));
        }

        public List<Sitecore.Data.Items.Item> GetItems()
        {
            var items = new List<Sitecore.Data.Items.Item>();
            var searchIndex = ContentSearchManager.GetIndex("sitecore_web_index"); // Get the search index
            
            using (var searchContext = searchIndex.CreateSearchContext()) // Get a context of the search index
            {
                var searchResults = searchContext.GetQueryable<SearchBlog>().Where(x => x.TemplateID == "bd77ee380e0942caa0f9d9ce322e4de6");
                var fullResults = searchResults.GetResults();

                foreach (var hit in fullResults.Hits)
                {
                    items.Add(Sitecore.Context.Database.GetItem(hit.Document.BlogId));
                }

                return items.Where(x => x != null).ToList();
            }
        }

        /// <summary>
        /// Search logic
        /// </summary>
        /// <param name="searchText">Search term</param>
        /// <returns>Search predicate object</returns>
        public static Expression<Func<SearchBlog, bool>> GetSearchPredicate(string searchText)
        {
            var predicate = PredicateBuilder.True<SearchBlog>();

            predicate = predicate.Or(x => x.BlogName.Contains(searchText));
            predicate = predicate.Or(x => x.BlogTitle.Contains(searchText));
            predicate = predicate.Or(x => x.ShortDescription.Contains(searchText));
            predicate = predicate.Or(x => x.LongDescription.Contains(searchText)); // .Boost(2.0f);

            //predicate = predicate.Or(x => x.Title.Contains(searchText)); // .Boost(2.0f);
            //Where Author="searchText" OR Description="searchText" OR Title="searchText"
            return predicate;
        }
    }
}

SitecoreBlog/Views/SitecoreBlog/404NotFound.cshtml
<main role="main" class="container blog-post-detail">
        <div>
               <h1 color="red">
                   Page not found
               </h1>
        </div>
    </main>

SitecoreBlog/Views/SitecoreBlog/ArticleBody.cshtml
<main role="main" class="container blog-post-detail">
        <div class="row">
            <div class="blog-post-detail-card card col-lg-12">
                @Html.Sitecore().Field("blogImage")
                <div class="card-body bg-light">
                    <strong class="d-inline-block mb-2 text-success">
                      @Html.Sitecore().Field("topic")
                    </strong>
                    <h3 class="card-title">
                      @Html.Sitecore().Field("title")
                    </h3>
                    <div class="mb-1 text-muted">
                      @Html.Sitecore().Field("postedDate")
                    </div>
                    <p>
                      @Html.Sitecore().Field("longDescription")
                    </p>
                    <div class="blog-detail-tag-list"><span class="read-more-heading">Read more: </span>
                        <a class="btn btn-info" href="#" role="button">Tag</a>
                        <a class="btn btn-info" href="#" role="button">Super Extra Long Tag</a>
                        <a class="btn btn-info" href="#" role="button">Extra Long Tag</a>
                    </div>
                </div>
            </div>
        </div>
    </main>

SitecoreBlog/Views/SitecoreBlog/ArticleCard.cshtml
<div class="blog-post-card card col-lg-4 col-md-6">
        <img class="card-img-top" src="assets/images/developer.jpg" alt="Card image cap">
        <div class="card-body bg-light">
          <strong class="d-inline-block mb-2 text-success">
            @Html.Sitecore().Field("topic")
          </strong>
          <h3 class="card-title">
            @Html.Sitecore().Field("title")
          </h3>
          <div class="mb-1 text-muted">
            @Html.Sitecore().Field("postedDate")
          </div>
          <p>
            @Html.Sitecore().Field("shortDescription")
          </p>
    <a href="#" class="btn btn-warning btn-block">Read on</a>
  </div>
</div>

SitecoreBlog/Views/SitecoreBlog/ArticleList.cshtml
@using System.Collections;
@using System;

@{
}
@model IEnumerable<Sitecore.Data.Items.Item>

<main role="main" class="container blog-posts">

    <div class="main-search">
        <div class="input-group">
            <form class="input-group" method="get" action="@Url.Action("DoSearch", "SitecoreBlog")">
                <input type="text" name="searchText" />
                <button class="btn btn-dark" id="searchButton" type="submit">Search</button>
            </form>
        </div>
    </div>
    <br>

    <div class="row" id="resultsItem">
        @if (Model != null)
        {
            foreach (Sitecore.Data.Items.Item item in Model)
            {
                <div class="blog-post-card card col-lg-4 col-md-6">
                    @Html.Sitecore().Field("blogImage", item, new { format = "MMM dd,yyyy", @class = "card-img-top" })
                    <div class="card-body bg-light">
                        <strong class="d-inline-block mb-2 text-success">
                            @Html.Sitecore().Field("topic", item)
                        </strong>
                        <h3 class="card-title">
                            @Html.Sitecore().Field("title", item)
                        </h3>
                        <div class="mb-1 text-muted">
                            @Html.Sitecore().Field("postedDate", item, new { format = "MMM dd, yyyy" })
                        </div>
                        <p>
                            @Html.Sitecore().Field("shortDescription", item)
                        </p>
                        @{
                            var url = Sitecore.Links.LinkManager.GetItemUrl(item);
                            <a href="@url" class="btn btn-warning btn-block">Read on</a>
                        }
                    </div>
                </div>
            }

        }
    </div>
</main>


<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
<script>
		$(document).ready(function () {
			$("#searchButton").click(function (e) {
				// debugger;
				e.preventDefault();
				$.ajax({
					type: "GET",
					datatype: "JSON", url: "@Url.Action("DoSearch", "SitecoreBlog")",
					contentType: "application/json",
					data: {
						searchText: $("#searchInput").val()
					},
					success: function (result) {
						var resultText = "";
						$('#resultsItem').text(resultText);
						$('#resultsItem').append("Results from SOLR index <BR><BR>");
						$(result.Results).each(function (index, item) {
							// each iteration
							//var Description = item.Description;
							//var Title = item.Title;
							//var Author = item.Author;
							//var ItemName = item.ItemName;
							//resultText += (index + 1) + " - " + ItemName + Title + "; " + Author + "; " + Description + "; " + "<BR><BR>";
							var BlogId = item.BlogId;
							var BlogTitle = item.BlogTitle;
                            resultText += (index + 1) + " - " + BlogId + " - " + BlogTitle + "; " + "<BR><BR>";
						});
						$('#resultsItem').append(resultText);
					},
					error: function (result) {
						alert('error');
                        console.error(result);
					}
				});
			});
		});
</script>

SitecoreBlog/Views/SitecoreBlog/ControllerDemo.cshtml
@model Sitecore.Data.Items.Item

<div>
    Way 1 - @Model["WebsiteHeading"]
    <br />
    Way 2 - @Model.Fields["WebsiteHeading"].Value
</div>	

SitecoreBlog/Views/SitecoreBlog/DefaultLayout.cshtml
@using Sitecore.Mvc
@using Sitecore.Mvc.Analytics.Extensions
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
    <head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="~/Content/bootstrap-themed.min.css" type="text/css">
  <link rel="stylesheet" href="~/Content/blogsite.css" type="text/css">
  
  <title>Sitecore Powered Blog</title>

</head>

<body>

  @Html.Sitecore().Placeholder("phHeader")


  @Html.Sitecore().Placeholder("phMain")


  @Html.Sitecore().Placeholder("phFooter")

</body>
</html>

SitecoreBlog/Views/SitecoreBlog/Footer.cshtml
<Footer>
    <div class="container">
      <div class="text-white bg-primary">
        <p class="lead">Copyright @@ 2021</p>
      </div>
    </div>
</Footer>

SitecoreBlog/Views/SitecoreBlog/Header.cshtml
@{
    var item = Sitecore.Context.Database.GetItem("/sitecore/content/Home/SitecoreBlog/SiteSettings/GlobalSetting");
    String hourString = DateTime.Now.ToString("HH");
    int hour = int.Parse(hourString);
    string backgroundColor = "darkblue";
    if (hour >= 17 && hour <= 7)
    {
        backgroundColor = "black";
    }
}

<header>
    <div class="container" style="background-color:@backgroundColor;">
        <div class="jumbotron text-white" style="background-color:@backgroundColor;">
            <h1 class="display-3">Sitecore Powered Blog</h1>
            <p class="lead">
                <a href="https://jss.sitecore.com/" class="text-light">
                    @item.Fields["WebsiteHeading"].Value
                </a>
                @item.Fields["WebsiteSubheading"].Value
            </p>
        </div>
    </div>
</header>

SitecoreBlog/Views/SitecoreBlog/Index.cshtml
@using System.Collections;
@using System;
@using System.Globalization;
@{
}
@model IEnumerable<Sitecore.Data.Items.Item>

@RenderPage("Header.cshtml")

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/Content/bootstrap-themed.min.css" type="text/css">
    <link rel="stylesheet" href="~/Content/blogsite.css" type="text/css">

    <title>Sitecore Powered Blog</title>

</head>

<body>

    <main role="main" class="container blog-posts">

        <div class="main-search">
            <div class="input-group">
                <form class="input-group" method="get" action="@Url.Action("DoSearch", "SitecoreBlog")">
                    <input type="text" name="searchText" />
                    <button class="btn btn-dark" id="searchButton" type="submit">Search</button>
                </form>
            </div>
        </div>
        <br>

        <div class="row" id="resultsItem">
            @if (Model != null)
                {
                    foreach (Sitecore.Data.Items.Item item in Model)
                    {
                        var mediaItem = ((Sitecore.Data.Fields.ImageField)item.Fields["BlogImage"]).MediaItem;

                        var imageHTML = Sitecore.Resources.Media.MediaManager.GetMediaUrl(mediaItem);
                        var postedDate = DateTime.ParseExact(item.Fields["PostedDate"].Value, "yyyyMMddTHHmmssZ", CultureInfo.InvariantCulture);
                        <div class="blog-post-card card col-lg-4 col-md-6">
                        <img class="card-img-top" src="@imageHTML" alt="Blog image" />

                        @*@Html.Sitecore().Field("blogImage", item, new { format = "MMM dd,yyyy", @class = "card-img-top" })*@
                        <div class="card-body bg-light">
                            <strong class="d-inline-block mb-2 text-success">
                                @Html.Raw(item.Fields["topic"].Value)
                            </strong>
                            <h3 class="card-title">
                                @Html.Raw(item.Fields["title"].Value)

                            </h3>
                            <div class="mb-1 text-muted">
                                
                                @postedDate
                            </div>
                            <p>
                                @Html.Raw(item.Fields["shortDescription"].Value)

                            </p>
                            @{
                                var url = Sitecore.Links.LinkManager.GetItemUrl(item);
                                <a href="@url" class="btn btn-warning btn-block">Read on</a>
                            }
                        </div>
                    </div>
                }

            }
        </div>
    </main>

    @RenderPage("Footer.cshtml")


    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
    <script>
		$(document).ready(function () {
			$("#searchButton").click(function (e) {
				// debugger;
				e.preventDefault();
				$.ajax({
					type: "GET",
					datatype: "JSON", url: "@Url.Action("DoSearch", "SitecoreBlog")",
					contentType: "application/json",
					data: {
						searchText: $("#searchInput").val()
					},
					success: function (result) {
						var resultText = "";
						$('#resultsItem').text(resultText);
						$('#resultsItem').append("Results from SOLR index <BR><BR>");
						$(result.Results).each(function (index, item) {
							// each iteration
							//var Description = item.Description;
							//var Title = item.Title;
							//var Author = item.Author;
							//var ItemName = item.ItemName;
							//resultText += (index + 1) + " - " + ItemName + Title + "; " + Author + "; " + Description + "; " + "<BR><BR>";
							var BlogId = item.BlogId;
							var BlogTitle = item.BlogTitle;
                            resultText += (index + 1) + " - " + BlogId + " - " + BlogTitle + "; " + "<BR><BR>";
						});
						$('#resultsItem').append(resultText);
					},
					error: function (result) {
						alert('error');
                        console.error(result);
					}
				});
			});
		});
    </script>
</body>

SitecoreBlog/Views/SitecoreBlog/Search.cshtml
@{
    ViewBag.Title = "SOLR Search Component";
}


<h2>Search Item</h2>
<div class="form-example">
    <label for="name">Search Item </label>
    <input type="text" name="name" id="searchInput" required>
</div>
<br />
<br />

<div class="form-example">
    <button class="favorite styled" type="button" id="searchButton">
        Search
    </button>
</div>

<div id="resultsItem"></div>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
<script>
		$(document).ready(function () {
			$("#searchButton").click(function (e) {
				// debugger;
				e.preventDefault();
				$.ajax({
					type: "GET",
					datatype: "JSON", url: "@Url.Action("DoSearch", "SitecoreBlog")",
					contentType: "application/json",
					data: {
						searchText: $("#searchInput").val()
					},
					success: function (result) {
						var resultText = "";
						$('#resultsItem').text(resultText);
						$('#resultsItem').append("Results from SOLR index <BR><BR>");
						$(result.Results).each(function (index, item) {
							// each iteration
							//var Description = item.Description;
							//var Title = item.Title;
							//var Author = item.Author;
							//var ItemName = item.ItemName;
							//resultText += (index + 1) + " - " + ItemName + Title + "; " + Author + "; " + Description + "; " + "<BR><BR>";
							var BlogId = item.BlogId;
							var BlogTitle = item.BlogTitle;
                            resultText += (index + 1) + " - " + BlogId + " - " + BlogTitle + "; " + "<BR><BR>";
						});
						$('#resultsItem').append(resultText);
					},
					error: function (result) {
						alert('error');
                        console.error(result);
					}
				});
			});
		});
</script>